name: Maven CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the Repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # You can adjust the Java version
        cache: 'maven'

    - name: Compile the Project
      run: mvn compile

    - name: Package the Application
      run: mvn package

    - name: Find and Upload Artifact
      run: |
        # Find the JAR file
        JAR_FILE=$(find . -name "*.jar" -type f)
        
        if [ -z "$JAR_FILE" ]; then
          echo "No JAR file found."
          exit 1
        fi

        # Print the found JAR file
        echo "Found JAR file: $JAR_FILE"

        # Upload the JAR file as an artifact
        echo "Uploading artifact..."
        mv $JAR_FILE my-application.jar
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-application-artifact
        path: my-application.jar
