name: Maven CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the Repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # You can adjust the Java version
        cache: 'maven'

    - name: Compile the Project
      run: mvn compile
