name: Maven CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the Repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # You can adjust the Java version
        cache: 'maven'

    - name: Compile the Project
      run: mvn compile

    - name: Package the Application
      run: mvn package

    - name: Create Artifacts Directory
      run: mkdir -p artifacts

    - name: Find and Move JAR file
      run: |
        JAR_FILE=$(find . -name "*.jar" -type f)
        if [ -z "$JAR_FILE" ]; then
          echo "No JAR file found."
          exit 1
        fi
        echo "Found JAR file: $JAR_FILE"
        mv $JAR_FILE artifacts/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifacts/
